# Generated by Django 2.2.19 on 2022-07-14 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GameImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.TextField(max_length=2047)),
                ('background_img', models.TextField(max_length=2047)),
                ('screenshot1', models.TextField(max_length=2047)),
                ('screenshot2', models.TextField(max_length=2047)),
                ('screenshot3', models.TextField(max_length=2047)),
                ('screenshot4', models.TextField(max_length=2047)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webproj_api.Game')),
            ],
            options={
                'verbose_name': 'Game Images',
                'verbose_name_plural': 'Game Images',
            },
        ),
        migrations.CreateModel(
            name='GameDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.CharField(max_length=255)),
                ('genres', models.CharField(max_length=255)),
                ('metacritic_points', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webproj_api.Game')),
            ],
            options={
                'verbose_name': 'Game Images',
                'verbose_name_plural': 'Game Images',
            },
        ),
        migrations.CreateModel(
            name='GameDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2047)),
                ('website_url', models.TextField(max_length=2047)),
                ('publisher', models.CharField(max_length=255)),
                ('platforms', models.CharField(max_length=255)),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webproj_api.Game')),
            ],
            options={
                'verbose_name': 'Game Description',
                'verbose_name_plural': 'Game Description',
            },
        ),
    ]
